/*-----------------------------------------------------------------------------
    Name: Login
    Recorded By: anjali
    Date of recording: 04/28/2017 01:24:16
    Flow details:
    Build details: 4.1.6 (build# 56)
    Modification History:
-----------------------------------------------------------------------------*/
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ns_string.h"

void Login()
{
	ns_advance_param("CloudEnvFP");
	char DPClusterbuff1[64 + 1]="";   
    snprintf(DPClusterbuff1,64,"%s",ns_eval_string("{CookieFP}"));
    ns_add_cookie_val_ex("DPCluster", NULL, NULL, DPClusterbuff1);


// Setting AWS Cloud header

    char cloudEnv[64 + 1]="";
	snprintf(cloudEnv,64,"%s",ns_eval_string("{CloudEnvFP}"));
    ns_web_add_auto_header("X-JCPCloud-Origin", cloudEnv, 0);
    
    
        
	ns_web_add_auto_header("Origin", "https://www.jcpenney.com", 0);
	
	 // ClickOn My Account
	int Exituser = ns_get_random_number_int(1,100);
	ns_start_transaction("COM_CAM_ClickOnMyAccount");
    ns_web_url ("ClickOnMyAccountPage1_1",
        "URL=https://www.jcpenney.com/signin",
        "HEADER=Upgrade-Insecure-Requests:1",
        "HEADER=Accept-Language:en-US,en;q=0.8",
        INLINE_URLS,
            "URL=https://www.jcpenney.com/dotcom/css/dotcom_global_cssBundle.css?v=2017.5.1.0.7.0", "HEADER=Accept-Language:en-us", "COOKIE=DPJSESSIONID;DPSessionTimeOutInterval;userLatLong;DPUserTracking;AKJCP;cmTPSet;marketing;TLTSID;__gads;AMCVS_CEEB350F5746CDE97F000101%40AdobeOrg;AMCV_CEEB350F5746CDE97F000101%40AdobeOrg;shipToCurrencyCode;shipToCountry;mbox;c17;v53;s_cc;_ga;s_ptc;_uetsid;RES_TRACKINGID;ResonanceSegment;RES_SESSIONID;CavSF;_gat;s_sq;_4c_;CavNVC;DPInstance;LegacyIdentifier;DPIdentifier;DPCluster;DPLastAccessedTime;InternationalItemTotal;ItemTotal;ItemCount;DPOrder;DP_USER_FAVCOUNT;DP_SFL_PPIDS;DP_USER_AUTH_STATUS", END_INLINE,
            "URL=https://www.jcpenney.com/dotcom/css/dotcom_dotcom_cssBundle.css?v=2017.5.1.0.7.0", "HEADER=Accept-Language:en-us", "COOKIE=DPJSESSIONID;DPSessionTimeOutInterval;userLatLong;DPUserTracking;AKJCP;cmTPSet;marketing;TLTSID;__gads;AMCVS_CEEB350F5746CDE97F000101%40AdobeOrg;AMCV_CEEB350F5746CDE97F000101%40AdobeOrg;shipToCurrencyCode;shipToCountry;mbox;c17;v53;s_cc;_ga;s_ptc;_uetsid;RES_TRACKINGID;ResonanceSegment;RES_SESSIONID;CavSF;_gat;s_sq;_4c_;CavNVC;DPInstance;LegacyIdentifier;DPIdentifier;DPCluster;DPLastAccessedTime;InternationalItemTotal;ItemTotal;ItemCount;DPOrder;DP_USER_FAVCOUNT;DP_SFL_PPIDS;DP_USER_AUTH_STATUS", END_INLINE,
            "URL=https://www.jcpenney.com/dotcom/css/checkout-lowresolution.css?v=2017.5.1.0.7.0", "HEADER=Accept-Language:en-us", "COOKIE=DPJSESSIONID;DPSessionTimeOutInterval;userLatLong;DPUserTracking;AKJCP;cmTPSet;marketing;TLTSID;__gads;AMCVS_CEEB350F5746CDE97F000101%40AdobeOrg;AMCV_CEEB350F5746CDE97F000101%40AdobeOrg;shipToCurrencyCode;shipToCountry;mbox;c17;v53;s_cc;_ga;s_ptc;_uetsid;RES_TRACKINGID;ResonanceSegment;RES_SESSIONID;CavSF;_gat;s_sq;_4c_;CavNVC;DPInstance;LegacyIdentifier;DPIdentifier;DPCluster;DPLastAccessedTime;InternationalItemTotal;ItemTotal;ItemCount;DPOrder;DP_USER_FAVCOUNT;DP_SFL_PPIDS;DP_USER_AUTH_STATUS", END_INLINE,
            "URL=https://www.jcpenney.com/dotcom/js/bundleJS/dotcom_global_jsBundle.js?v=2017.5.1.0.7.0", "HEADER=Accept-Language:en-us", "COOKIE=DPJSESSIONID;DPSessionTimeOutInterval;userLatLong;DPUserTracking;AKJCP;cmTPSet;marketing;TLTSID;__gads;AMCVS_CEEB350F5746CDE97F000101%40AdobeOrg;AMCV_CEEB350F5746CDE97F000101%40AdobeOrg;shipToCurrencyCode;shipToCountry;mbox;c17;v53;s_cc;_ga;s_ptc;_uetsid;RES_TRACKINGID;ResonanceSegment;RES_SESSIONID;CavSF;_gat;s_sq;_4c_;CavNVC;DPInstance;LegacyIdentifier;DPIdentifier;DPCluster;DPLastAccessedTime;InternationalItemTotal;ItemTotal;ItemCount;DPOrder;DP_USER_FAVCOUNT;DP_SFL_PPIDS;DP_USER_AUTH_STATUS", END_INLINE,
            "URL=https://www.jcpenney.com/dotcom/js/bundleJS/dotcom_dotcom_jsBundle.js?v=2017.5.1.0.7.0", "HEADER=Accept-Language:en-us", "COOKIE=DPJSESSIONID;DPSessionTimeOutInterval;userLatLong;DPUserTracking;AKJCP;cmTPSet;marketing;TLTSID;__gads;AMCVS_CEEB350F5746CDE97F000101%40AdobeOrg;AMCV_CEEB350F5746CDE97F000101%40AdobeOrg;shipToCurrencyCode;shipToCountry;mbox;c17;v53;s_cc;_ga;s_ptc;_uetsid;RES_TRACKINGID;ResonanceSegment;RES_SESSIONID;CavSF;_gat;s_sq;_4c_;CavNVC;DPInstance;LegacyIdentifier;DPIdentifier;DPCluster;DPLastAccessedTime;InternationalItemTotal;ItemTotal;ItemCount;DPOrder;DP_USER_FAVCOUNT;DP_SFL_PPIDS;DP_USER_AUTH_STATUS", END_INLINE,
            "URL=https://nexus.ensighten.com/jcpenney/Bootstrap.js", "HEADER=Accept-Language:en-us", END_INLINE,
            "URL=https://www.jcpenney.com/cam/js/lib/jquery.form.js?v=2017.5.1.0.7.0", "HEADER=Accept-Language:en-us", "COOKIE=DPJSESSIONID;DPSessionTimeOutInterval;userLatLong;DPUserTracking;AKJCP;cmTPSet;marketing;TLTSID;__gads;AMCVS_CEEB350F5746CDE97F000101%40AdobeOrg;AMCV_CEEB350F5746CDE97F000101%40AdobeOrg;shipToCurrencyCode;shipToCountry;mbox;c17;v53;s_cc;_ga;s_ptc;_uetsid;RES_TRACKINGID;ResonanceSegment;RES_SESSIONID;CavSF;_gat;s_sq;_4c_;CavNVC;DPInstance;LegacyIdentifier;DPIdentifier;DPCluster;DPLastAccessedTime;InternationalItemTotal;ItemTotal;ItemCount;DPOrder;DP_USER_FAVCOUNT;DP_SFL_PPIDS;DP_USER_AUTH_STATUS", END_INLINE,
            "URL=https://www.jcpenney.com/cam/js/common_validations.js?v=2017.5.1.0.7.0", "HEADER=Accept-Language:en-us", "COOKIE=DPJSESSIONID;DPSessionTimeOutInterval;userLatLong;DPUserTracking;AKJCP;cmTPSet;marketing;TLTSID;__gads;AMCVS_CEEB350F5746CDE97F000101%40AdobeOrg;AMCV_CEEB350F5746CDE97F000101%40AdobeOrg;shipToCurrencyCode;shipToCountry;mbox;c17;v53;s_cc;_ga;s_ptc;_uetsid;RES_TRACKINGID;ResonanceSegment;RES_SESSIONID;CavSF;_gat;s_sq;_4c_;CavNVC;DPInstance;LegacyIdentifier;DPIdentifier;DPCluster;DPLastAccessedTime;InternationalItemTotal;ItemTotal;ItemCount;DPOrder;DP_USER_FAVCOUNT;DP_SFL_PPIDS;DP_USER_AUTH_STATUS", END_INLINE,
            "URL=https://www.jcpenney.com/cam/js/captcha.js?v=2017.5.1.0.7.0", "HEADER=Accept-Language:en-us", "COOKIE=DPJSESSIONID;DPSessionTimeOutInterval;userLatLong;DPUserTracking;AKJCP;cmTPSet;marketing;TLTSID;__gads;AMCVS_CEEB350F5746CDE97F000101%40AdobeOrg;AMCV_CEEB350F5746CDE97F000101%40AdobeOrg;shipToCurrencyCode;shipToCountry;mbox;c17;v53;s_cc;_ga;s_ptc;_uetsid;RES_TRACKINGID;ResonanceSegment;RES_SESSIONID;CavSF;_gat;s_sq;_4c_;CavNVC;DPInstance;LegacyIdentifier;DPIdentifier;DPCluster;DPLastAccessedTime;InternationalItemTotal;ItemTotal;ItemCount;DPOrder;DP_USER_FAVCOUNT;DP_SFL_PPIDS;DP_USER_AUTH_STATUS", END_INLINE,
            "URL=https://www.jcpenney.com/dotcom/js/bundleJS/dotcom_signInHeader_common_jsBundle.js?v=2017.5.1.0.7.0", "HEADER=Accept-Language:en-us", "COOKIE=DPJSESSIONID;DPSessionTimeOutInterval;userLatLong;DPUserTracking;AKJCP;cmTPSet;marketing;TLTSID;__gads;AMCVS_CEEB350F5746CDE97F000101%40AdobeOrg;AMCV_CEEB350F5746CDE97F000101%40AdobeOrg;shipToCurrencyCode;shipToCountry;mbox;c17;v53;s_cc;_ga;s_ptc;_uetsid;RES_TRACKINGID;ResonanceSegment;RES_SESSIONID;CavSF;_gat;s_sq;_4c_;CavNVC;DPInstance;LegacyIdentifier;DPIdentifier;DPCluster;DPLastAccessedTime;InternationalItemTotal;ItemTotal;ItemCount;DPOrder;DP_USER_FAVCOUNT;DP_SFL_PPIDS;DP_USER_AUTH_STATUS", END_INLINE,
            "URL=https://www.jcpenney.com/dotcom/js/bumperSiteLists.js?v=2017.5.1.0.7.0", "HEADER=Accept-Language:en-us", "COOKIE=DPJSESSIONID;DPSessionTimeOutInterval;userLatLong;DPUserTracking;AKJCP;cmTPSet;marketing;TLTSID;__gads;AMCVS_CEEB350F5746CDE97F000101%40AdobeOrg;AMCV_CEEB350F5746CDE97F000101%40AdobeOrg;shipToCurrencyCode;shipToCountry;mbox;c17;v53;s_cc;_ga;s_ptc;_uetsid;RES_TRACKINGID;ResonanceSegment;RES_SESSIONID;CavSF;_gat;s_sq;_4c_;CavNVC;DPInstance;LegacyIdentifier;DPIdentifier;DPCluster;DPLastAccessedTime;InternationalItemTotal;ItemTotal;ItemCount;DPOrder;DP_USER_FAVCOUNT;DP_SFL_PPIDS;DP_USER_AUTH_STATUS", END_INLINE,
            "URL=https://www.jcpenney.com/cam/js/lib/jquery.ba-postmessage.js?v=2017.5.1.0.7.0", "HEADER=Accept-Language:en-us", "COOKIE=DPJSESSIONID;DPSessionTimeOutInterval;userLatLong;DPUserTracking;AKJCP;cmTPSet;marketing;TLTSID;__gads;AMCVS_CEEB350F5746CDE97F000101%40AdobeOrg;AMCV_CEEB350F5746CDE97F000101%40AdobeOrg;shipToCurrencyCode;shipToCountry;mbox;c17;v53;s_cc;_ga;s_ptc;_uetsid;RES_TRACKINGID;ResonanceSegment;RES_SESSIONID;CavSF;_gat;s_sq;_4c_;CavNVC;DPInstance;LegacyIdentifier;DPIdentifier;DPCluster;DPLastAccessedTime;InternationalItemTotal;ItemTotal;ItemCount;DPOrder;DP_USER_FAVCOUNT;DP_SFL_PPIDS;DP_USER_AUTH_STATUS", END_INLINE,
            "URL=https://www.jcpenney.com/dotcom/js/localStoreSearch.js?v=2017.5.1.0.7.0", "HEADER=Accept-Language:en-us", "COOKIE=DPJSESSIONID;DPSessionTimeOutInterval;userLatLong;DPUserTracking;AKJCP;cmTPSet;marketing;TLTSID;__gads;AMCVS_CEEB350F5746CDE97F000101%40AdobeOrg;AMCV_CEEB350F5746CDE97F000101%40AdobeOrg;shipToCurrencyCode;shipToCountry;mbox;c17;v53;s_cc;_ga;s_ptc;_uetsid;RES_TRACKINGID;ResonanceSegment;RES_SESSIONID;CavSF;_gat;s_sq;_4c_;CavNVC;DPInstance;LegacyIdentifier;DPIdentifier;DPCluster;DPLastAccessedTime;InternationalItemTotal;ItemTotal;ItemCount;DPOrder;DP_USER_FAVCOUNT;DP_SFL_PPIDS;DP_USER_AUTH_STATUS", END_INLINE,
            "URL=https://www.jcpenney.com/dotcom/js/lib/jquery.dotdotdot.js?v=2017.5.1.0.7.0", "HEADER=Accept-Language:en-us", "COOKIE=DPJSESSIONID;DPSessionTimeOutInterval;userLatLong;DPUserTracking;AKJCP;cmTPSet;marketing;TLTSID;__gads;AMCVS_CEEB350F5746CDE97F000101%40AdobeOrg;AMCV_CEEB350F5746CDE97F000101%40AdobeOrg;shipToCurrencyCode;shipToCountry;mbox;c17;v53;s_cc;_ga;s_ptc;_uetsid;RES_TRACKINGID;ResonanceSegment;RES_SESSIONID;CavSF;_gat;s_sq;_4c_;CavNVC;DPInstance;LegacyIdentifier;DPIdentifier;DPCluster;DPLastAccessedTime;InternationalItemTotal;ItemTotal;ItemCount;DPOrder;DP_USER_FAVCOUNT;DP_SFL_PPIDS;DP_USER_AUTH_STATUS", END_INLINE,
            "URL=https://www.jcpenney.com/dotcom/js/lib/underscore-min-1.4.2.js?v=2017.5.1.0.7.0", "HEADER=Accept-Language:en-us", "COOKIE=DPJSESSIONID;DPSessionTimeOutInterval;userLatLong;DPUserTracking;AKJCP;cmTPSet;marketing;TLTSID;__gads;AMCVS_CEEB350F5746CDE97F000101%40AdobeOrg;AMCV_CEEB350F5746CDE97F000101%40AdobeOrg;shipToCurrencyCode;shipToCountry;mbox;c17;v53;s_cc;_ga;s_ptc;_uetsid;RES_TRACKINGID;ResonanceSegment;RES_SESSIONID;CavSF;_gat;s_sq;_4c_;CavNVC;DPInstance;LegacyIdentifier;DPIdentifier;DPCluster;DPLastAccessedTime;InternationalItemTotal;ItemTotal;ItemCount;DPOrder;DP_USER_FAVCOUNT;DP_SFL_PPIDS;DP_USER_AUTH_STATUS", END_INLINE,
            "URL=https://www.jcpenney.com/dotcom/js/typeahead.js?v=2017.5.1.0.7.0", "HEADER=Accept-Language:en-us", "COOKIE=DPJSESSIONID;DPSessionTimeOutInterval;userLatLong;DPUserTracking;AKJCP;cmTPSet;marketing;TLTSID;__gads;AMCVS_CEEB350F5746CDE97F000101%40AdobeOrg;AMCV_CEEB350F5746CDE97F000101%40AdobeOrg;shipToCurrencyCode;shipToCountry;mbox;c17;v53;s_cc;_ga;s_ptc;_uetsid;RES_TRACKINGID;ResonanceSegment;RES_SESSIONID;CavSF;_gat;s_sq;_4c_;CavNVC;DPInstance;LegacyIdentifier;DPIdentifier;DPCluster;DPLastAccessedTime;InternationalItemTotal;ItemTotal;ItemCount;DPOrder;DP_USER_FAVCOUNT;DP_SFL_PPIDS;DP_USER_AUTH_STATUS", END_INLINE,
            "URL=https://www.jcpenney.com/dotcom/js/bundleJS/dotcom_footer_global_jsBundle.js?v=2017.5.1.0.7.0", "HEADER=Accept-Language:en-us", "COOKIE=DPJSESSIONID;DPSessionTimeOutInterval;userLatLong;DPUserTracking;AKJCP;cmTPSet;marketing;TLTSID;__gads;AMCVS_CEEB350F5746CDE97F000101%40AdobeOrg;AMCV_CEEB350F5746CDE97F000101%40AdobeOrg;shipToCurrencyCode;shipToCountry;mbox;c17;v53;s_cc;_ga;s_ptc;_uetsid;RES_TRACKINGID;ResonanceSegment;RES_SESSIONID;CavSF;_gat;s_sq;_4c_;CavNVC;DPInstance;LegacyIdentifier;DPIdentifier;DPCluster;DPLastAccessedTime;InternationalItemTotal;ItemTotal;ItemCount;DPOrder;DP_USER_FAVCOUNT;DP_SFL_PPIDS;DP_USER_AUTH_STATUS", END_INLINE,
            "URL=https://www.jcpenney.com/cam/js/lib/eluminate.js?v=2017.5.1.0.7.0", "HEADER=Accept-Language:en-us", "COOKIE=DPJSESSIONID;DPSessionTimeOutInterval;userLatLong;DPUserTracking;AKJCP;cmTPSet;marketing;TLTSID;__gads;AMCVS_CEEB350F5746CDE97F000101%40AdobeOrg;AMCV_CEEB350F5746CDE97F000101%40AdobeOrg;shipToCurrencyCode;shipToCountry;mbox;c17;v53;s_cc;_ga;s_ptc;_uetsid;RES_TRACKINGID;ResonanceSegment;RES_SESSIONID;CavSF;_gat;s_sq;_4c_;CavNVC;DPInstance;LegacyIdentifier;DPIdentifier;DPCluster;DPLastAccessedTime;InternationalItemTotal;ItemTotal;ItemCount;DPOrder;DP_USER_FAVCOUNT;DP_SFL_PPIDS;DP_USER_AUTH_STATUS", END_INLINE,
            "URL=https://www.jcpenney.com/dotcom/images/logo.gif", "HEADER=Accept-Language:en-us", "COOKIE=DPJSESSIONID;DPSessionTimeOutInterval;userLatLong;DPUserTracking;AKJCP;cmTPSet;marketing;TLTSID;__gads;AMCVS_CEEB350F5746CDE97F000101%40AdobeOrg;AMCV_CEEB350F5746CDE97F000101%40AdobeOrg;shipToCurrencyCode;shipToCountry;mbox;c17;v53;s_cc;_ga;s_ptc;_uetsid;RES_TRACKINGID;ResonanceSegment;RES_SESSIONID;CavSF;_gat;s_sq;_4c_;CavNVC;DPInstance;DPCluster;DPLastAccessedTime;InternationalItemTotal;ItemTotal;ItemCount;DPOrder;DP_USER_FAVCOUNT;DP_SFL_PPIDS;DP_USER_AUTH_STATUS;DPIdentifier;LegacyIdentifier", END_INLINE,
            "URL=https://www.jcpenney.com/cam/images/spacer.gif", "HEADER=Accept-Language:en-us", "COOKIE=DPJSESSIONID;DPSessionTimeOutInterval;userLatLong;DPUserTracking;AKJCP;cmTPSet;marketing;TLTSID;__gads;AMCVS_CEEB350F5746CDE97F000101%40AdobeOrg;AMCV_CEEB350F5746CDE97F000101%40AdobeOrg;shipToCurrencyCode;shipToCountry;mbox;c17;v53;s_cc;_ga;s_ptc;_uetsid;RES_TRACKINGID;ResonanceSegment;RES_SESSIONID;CavSF;_gat;s_sq;_4c_;CavNVC;DPInstance;DPCluster;DPLastAccessedTime;InternationalItemTotal;ItemTotal;ItemCount;DPOrder;DP_USER_FAVCOUNT;DP_SFL_PPIDS;DP_USER_AUTH_STATUS;DPIdentifier;LegacyIdentifier", END_INLINE,
            "URL=https://www.jcpenney.com/cam/images/icon-express-checkout.svg", "HEADER=Accept-Language:en-us", "COOKIE=DPJSESSIONID;DPSessionTimeOutInterval;userLatLong;DPUserTracking;AKJCP;cmTPSet;marketing;TLTSID;__gads;AMCVS_CEEB350F5746CDE97F000101%40AdobeOrg;AMCV_CEEB350F5746CDE97F000101%40AdobeOrg;shipToCurrencyCode;shipToCountry;mbox;c17;v53;s_cc;_ga;s_ptc;_uetsid;RES_TRACKINGID;ResonanceSegment;RES_SESSIONID;CavSF;_gat;s_sq;_4c_;CavNVC;DPInstance;DPCluster;DPLastAccessedTime;InternationalItemTotal;ItemTotal;ItemCount;DPOrder;DP_USER_FAVCOUNT;DP_SFL_PPIDS;DP_USER_AUTH_STATUS;DPIdentifier;LegacyIdentifier", END_INLINE,
            "URL=https://www.jcpenney.com/cam/images/list.svg", "HEADER=Accept-Language:en-us", "COOKIE=DPJSESSIONID;DPSessionTimeOutInterval;userLatLong;DPUserTracking;AKJCP;cmTPSet;marketing;TLTSID;__gads;AMCVS_CEEB350F5746CDE97F000101%40AdobeOrg;AMCV_CEEB350F5746CDE97F000101%40AdobeOrg;shipToCurrencyCode;shipToCountry;mbox;c17;v53;s_cc;_ga;s_ptc;_uetsid;RES_TRACKINGID;ResonanceSegment;RES_SESSIONID;CavSF;_gat;s_sq;_4c_;CavNVC;DPInstance;DPCluster;DPLastAccessedTime;InternationalItemTotal;ItemTotal;ItemCount;DPOrder;DP_USER_FAVCOUNT;DP_SFL_PPIDS;DP_USER_AUTH_STATUS;DPIdentifier;LegacyIdentifier", END_INLINE,
            "URL=https://www.jcpenney.com/cam/images/icon-mobile.svg", "HEADER=Accept-Language:en-us", "COOKIE=DPJSESSIONID;DPSessionTimeOutInterval;userLatLong;DPUserTracking;AKJCP;cmTPSet;marketing;TLTSID;__gads;AMCVS_CEEB350F5746CDE97F000101%40AdobeOrg;AMCV_CEEB350F5746CDE97F000101%40AdobeOrg;shipToCurrencyCode;shipToCountry;mbox;c17;v53;s_cc;_ga;s_ptc;_uetsid;RES_TRACKINGID;ResonanceSegment;RES_SESSIONID;CavSF;_gat;s_sq;_4c_;CavNVC;DPInstance;DPCluster;DPLastAccessedTime;InternationalItemTotal;ItemTotal;ItemCount;DPOrder;DP_USER_FAVCOUNT;DP_SFL_PPIDS;DP_USER_AUTH_STATUS;DPIdentifier;LegacyIdentifier", END_INLINE,
            "URL=https://www.jcpenney.com/cam/images/icon-coupon-rewards.svg", "HEADER=Accept-Language:en-us", "COOKIE=DPJSESSIONID;DPSessionTimeOutInterval;userLatLong;DPUserTracking;AKJCP;cmTPSet;marketing;TLTSID;__gads;AMCVS_CEEB350F5746CDE97F000101%40AdobeOrg;AMCV_CEEB350F5746CDE97F000101%40AdobeOrg;shipToCurrencyCode;shipToCountry;mbox;c17;v53;s_cc;_ga;s_ptc;_uetsid;RES_TRACKINGID;ResonanceSegment;RES_SESSIONID;CavSF;_gat;s_sq;_4c_;CavNVC;DPInstance;DPCluster;DPLastAccessedTime;InternationalItemTotal;ItemTotal;ItemCount;DPOrder;DP_USER_FAVCOUNT;DP_SFL_PPIDS;DP_USER_AUTH_STATUS;DPIdentifier;LegacyIdentifier", END_INLINE,
            "URL=https://www.jcpenney.com/cam/images/coupon-fill.svg", "HEADER=Accept-Language:en-us", "COOKIE=DPJSESSIONID;DPSessionTimeOutInterval;userLatLong;DPUserTracking;AKJCP;cmTPSet;marketing;TLTSID;__gads;AMCVS_CEEB350F5746CDE97F000101%40AdobeOrg;AMCV_CEEB350F5746CDE97F000101%40AdobeOrg;shipToCurrencyCode;shipToCountry;mbox;c17;v53;s_cc;_ga;s_ptc;_uetsid;RES_TRACKINGID;ResonanceSegment;RES_SESSIONID;CavSF;_gat;s_sq;_4c_;CavNVC;DPInstance;DPCluster;DPLastAccessedTime;InternationalItemTotal;ItemTotal;ItemCount;DPOrder;DP_USER_FAVCOUNT;DP_SFL_PPIDS;DP_USER_AUTH_STATUS;DPIdentifier;LegacyIdentifier", END_INLINE,
            "URL=https://www.jcpenney.com/cam/images/creditcard-top-banner.png", "HEADER=Accept-Language:en-us", "COOKIE=DPJSESSIONID;DPSessionTimeOutInterval;userLatLong;DPUserTracking;AKJCP;cmTPSet;marketing;TLTSID;__gads;AMCVS_CEEB350F5746CDE97F000101%40AdobeOrg;AMCV_CEEB350F5746CDE97F000101%40AdobeOrg;shipToCurrencyCode;shipToCountry;mbox;c17;v53;s_cc;_ga;s_ptc;_uetsid;RES_TRACKINGID;ResonanceSegment;RES_SESSIONID;CavSF;_gat;s_sq;_4c_;CavNVC;DPInstance;DPCluster;DPLastAccessedTime;InternationalItemTotal;ItemTotal;ItemCount;DPOrder;DP_USER_FAVCOUNT;DP_SFL_PPIDS;DP_USER_AUTH_STATUS;DPIdentifier;LegacyIdentifier", END_INLINE,
            "URL=https://www.jcpenney.com/dotcom/images/jcp_ad_choices.gif", "HEADER=Accept-Language:en-us", "COOKIE=DPJSESSIONID;DPSessionTimeOutInterval;userLatLong;DPUserTracking;AKJCP;cmTPSet;marketing;TLTSID;__gads;AMCVS_CEEB350F5746CDE97F000101%40AdobeOrg;AMCV_CEEB350F5746CDE97F000101%40AdobeOrg;shipToCurrencyCode;shipToCountry;mbox;c17;v53;s_cc;_ga;s_ptc;_uetsid;RES_TRACKINGID;ResonanceSegment;RES_SESSIONID;CavSF;_gat;s_sq;_4c_;CavNVC;DPInstance;DPCluster;DPLastAccessedTime;InternationalItemTotal;ItemTotal;ItemCount;DPOrder;DP_USER_FAVCOUNT;DP_SFL_PPIDS;DP_USER_AUTH_STATUS;DPIdentifier;LegacyIdentifier", END_INLINE,
            "URL=https://cdn.tt.omtrdc.net/cdn/target.js", "HEADER=Accept-Language:en-us", END_INLINE,
            "URL=https://nexus.ensighten.com/jcpenney/prod/serverComponent.php?r=59111.69718145397&ClientID=730&PageID=https%3A%2F%2Fwww.jcpenney.com%2Fcam%2Fjsp%2Fprofile%2Fsecure%2Flogin.jsp%3FisfromMyAccount%3Dtrue", "HEADER=Accept-Language:en-us", END_INLINE,
            "URL=https://nexus.ensighten.com/jcpenney/prod/code/88a70c01f7a0933a76e260c827fb3606.js?conditionId0=324309", "HEADER=Accept-Language:en-us", END_INLINE,
            "URL=https://nexus.ensighten.com/jcpenney/prod/code/5ab2c810e1acfb7862f287a7a83ac96a.js?conditionId0=335512", "HEADER=Accept-Language:en-us", END_INLINE,
            "URL=https://nexus.ensighten.com/jcpenney/prod/code/0f5a676ae1e8054f19c40224b4a93570.js?conditionId0=422808", "HEADER=Accept-Language:en-us", END_INLINE,
            "URL=https://nexus.ensighten.com/jcpenney/prod/code/6bba424f9de60b1dabf2c2f8fc07377e.js?conditionId0=335308", "HEADER=Accept-Language:en-us", END_INLINE,
            "URL=https://nexus.ensighten.com/jcpenney/prod/code/1167cee93f5d8b8e0d7246bf5796a826.js?conditionId0=460821", "HEADER=Accept-Language:en-us", END_INLINE,
            "URL=https://nexus.ensighten.com/jcpenney/prod/code/917c49a2004d2d8ef510e0d6f92ed48d.js?conditionId0=346182", "HEADER=Accept-Language:en-us", END_INLINE,
            "URL=https://www.jcpenney.com/cam/images/flags/US.gif", "HEADER=Accept-Language:en-us", "COOKIE=DPJSESSIONID;DPSessionTimeOutInterval;userLatLong;DPUserTracking;AKJCP;cmTPSet;marketing;TLTSID;__gads;AMCVS_CEEB350F5746CDE97F000101%40AdobeOrg;AMCV_CEEB350F5746CDE97F000101%40AdobeOrg;shipToCurrencyCode;shipToCountry;c17;v53;s_cc;_ga;s_ptc;_uetsid;RES_TRACKINGID;ResonanceSegment;RES_SESSIONID;CavSF;_gat;s_sq;_4c_;CavNVC;DPInstance;DPCluster;DPLastAccessedTime;InternationalItemTotal;ItemTotal;ItemCount;DPOrder;DP_USER_FAVCOUNT;DP_SFL_PPIDS;DP_USER_AUTH_STATUS;DPIdentifier;LegacyIdentifier;mbox", END_INLINE,
            "URL=https://nexus.ensighten.com/jcpenney/prod/code/41f82563a6c9143f9988199e47778234.js?conditionId0=443201", "HEADER=Accept-Language:en-us", END_INLINE,
            "URL=https://www.jcpenney.com/dotcom/images/sprites.png", "HEADER=Accept-Language:en-us", "COOKIE=DPJSESSIONID;DPSessionTimeOutInterval;userLatLong;DPUserTracking;AKJCP;cmTPSet;marketing;TLTSID;__gads;AMCVS_CEEB350F5746CDE97F000101%40AdobeOrg;AMCV_CEEB350F5746CDE97F000101%40AdobeOrg;shipToCurrencyCode;shipToCountry;c17;v53;s_cc;_ga;s_ptc;_uetsid;RES_TRACKINGID;ResonanceSegment;RES_SESSIONID;CavSF;_gat;s_sq;_4c_;CavNVC;DPInstance;DPCluster;DPLastAccessedTime;InternationalItemTotal;ItemTotal;ItemCount;DPOrder;DP_USER_FAVCOUNT;DP_SFL_PPIDS;DP_USER_AUTH_STATUS;DPIdentifier;LegacyIdentifier;mbox", END_INLINE,
            "URL=https://testlibs.coremetrics.com/configs/90024642.js", "HEADER=Accept-Language:en-us", END_INLINE,
            "URL=https://www88.jcpenney.com/cookie-id.js?fn=eluminate7981", "HEADER=Accept-Language:en-us", "COOKIE=DPJSESSIONID;DPSessionTimeOutInterval;userLatLong;DPUserTracking;AKJCP;CoreID6;TestSess3;90024642_login;marketing;TLTSID;__gads;AMCVS_CEEB350F5746CDE97F000101%40AdobeOrg;AMCV_CEEB350F5746CDE97F000101%40AdobeOrg;shipToCurrencyCode;shipToCountry;90024642_reset;_ga;_uetsid;RES_TRACKINGID;ResonanceSegment;RES_SESSIONID;_gat;_4c_;DPInstance;DPCluster;DPLastAccessedTime;InternationalItemTotal;ItemTotal;ItemCount;DPOrder;DP_USER_FAVCOUNT;DP_SFL_PPIDS;DP_USER_AUTH_STATUS;mbox;DPIdentifier;LegacyIdentifier", END_INLINE,
            "URL=https://www88.jcpenney.com/cm?ci=90024642&st=1493359865855&vn1=4.14.30&ec=utf-8&vn2=e4.0&pi=Login&rf=http%3A%2F%2Fwww.jcpenney.com%2F&ul=https%3A%2F%2Fwww.jcpenney.com%2Fcam%2Fjsp%2Fprofile%2Fsecure%2Flogin.jsp%3FisfromMyAccount%3Dtrue&tid=1&cg=JCP%7CCommunity&rnd=1493362422651", "HEADER=Accept-Language:en-us", "COOKIE=DPJSESSIONID;DPSessionTimeOutInterval;userLatLong;DPUserTracking;AKJCP;CoreID6;TestSess3;90024642_login;marketing;TLTSID;__gads;AMCVS_CEEB350F5746CDE97F000101%40AdobeOrg;AMCV_CEEB350F5746CDE97F000101%40AdobeOrg;shipToCurrencyCode;shipToCountry;90024642_reset;_ga;_uetsid;RES_TRACKINGID;ResonanceSegment;RES_SESSIONID;_gat;_4c_;DPInstance;DPCluster;DPLastAccessedTime;InternationalItemTotal;ItemTotal;ItemCount;DPOrder;DP_USER_FAVCOUNT;DP_SFL_PPIDS;DP_USER_AUTH_STATUS;mbox;DPIdentifier;LegacyIdentifier", END_INLINE,
            "URL=https://www.jcpenney.com/dotcom/images/loading.gif", "HEADER=Accept-Language:en-us", "COOKIE=DPJSESSIONID;DPSessionTimeOutInterval;userLatLong;DPUserTracking;AKJCP;cmTPSet;marketing;TLTSID;__gads;AMCVS_CEEB350F5746CDE97F000101%40AdobeOrg;AMCV_CEEB350F5746CDE97F000101%40AdobeOrg;shipToCurrencyCode;shipToCountry;c17;v53;s_cc;_ga;s_ptc;_uetsid;RES_TRACKINGID;ResonanceSegment;RES_SESSIONID;CavSF;_gat;s_sq;_4c_;CavNVC;DPInstance;DPCluster;DPLastAccessedTime;InternationalItemTotal;ItemTotal;ItemCount;DPOrder;DP_USER_FAVCOUNT;DP_SFL_PPIDS;DP_USER_AUTH_STATUS;mbox;DPIdentifier;LegacyIdentifier", END_INLINE
    );
    ns_end_transaction("COM_CAM_ClickOnMyAccount", NS_AUTO_STATUS);
    
    
	// Sign In
	//ns_start_transaction("COM_CAM_Login");
	ns_start_transaction("DT_API_CAM_OauthToken_OPTIONS");
         ns_web_url("API_CAM_OauthToken1_1",
        "URL=https://account-api.jcpenney.com/v5/oauth2/token",
        "METHOD=OPTIONS",
        "HEADER=Access-Control-Request-Method:POST",
        "HEADER=Access-Control-Request-Headers:authorization, content-type",
        "HEADER=Accept-Language:en-us",
        INLINE_URLS,
            "URL=https://jcpenney.d1.sc.omtrdc.net/b/ss/jcpenneyprod/1/JS-1.7.0/s4733174110221?AQB=1&ndh=1&pf=1&t=12%2F5%2F2017%202%3A53%3A42%201%20300&mid=45529909927814030712367151988437404809&aamlh=9&ce=UTF-8&ns=jcpenney&pageName=d%3Afindcoupon&g=https%3A%2F%2Fm.jcpenney.com%2Fcart&cc=USD&ch=checkout&server=DTAPIEXPR1L1J3_19&products=%3B1c41b57%3B1%3B20.00%3B%3Bevar6%3D5030205%7Cevar4%3Dnike%206-pk.%20performance%20cotton%20crew%20socks%7Cevar20%3Dsale%7Cevar32%3Dno%20rating%3Ano%20reviews%7Cevar34%3D50302050083%7Cevar35%3Dcongruent%7Cevar41%3Dship%20to%20store&c1=shopping%20cart&v1=D%3Dc1&c6=checkout%3Acheckout%20shopping%20cart&c7=http%3A%2F%2Fm.jcpenney.com%2Fcart&c11=d%3Acheckout%3Acheckout%20shopping%20cart&v11=D%3Dc11&v16=D%3DpageName&c17=r%3Acheckout%3Acheckout%20shopping%20cart&v17=D%3Dc17&c19=DU-2321669%2CMU-2321679%2CGT-2314509%2CABC-2314511%2CAET-2296995%2CAGV-2314512&c44=desktop&v44=D%3Dc44&v53=d%3Acheckout%3Acheckout%20shopping%20cart&pe=lnk_o&pev2=openModal&c.&a.&activitymap.&page=d%3Acheckout%3Acheckout%20shopping%20cart&link=FIND%20BEST%20COUPON&region=content&pageIDType=1&.activitymap&.a&.c&s=0x0&j=1.6&v=N&k=Y&bw=1366&bh=607&AQE=1", "HEADER=Yoda-checkout:true", "HEADER=DPCluster:L1", "HEADER=X-Auto-Login:true", "HEADER=Accept-Language:en-us", END_INLINE,
            "URL=https://va.v.liveperson.net/api/js/58507821?sid=aFKaaWZlQueDa41Ci38lzg&cb=lpCb75822x79794&t=ip&ts=1497254023074&pid=6684145455&tid=1033325825&vid=U5MTNjZGUzYjA2MjcyNTk1", "HEADER=Yoda-checkout:true", "HEADER=DPCluster:L1", "HEADER=X-Auto-Login:true", "HEADER=Accept-Language:en-us", "COOKIE=LPSessionID;LPVisitorID;DPCluster;Yoda-checkout", END_INLINE
    );
    ns_end_transaction("DT_API_CAM_OauthToken_OPTIONS",NS_AUTO_STATUS);
	 
    ns_start_transaction("DT_API_CAM_OauthToken_POST");
    ns_web_url ("SignInPage1_1",
        "URL=https://account-api.jcpenney.com/v5/oauth2/token",
        "METHOD=POST",
        "HEADER=content-type:application/json;charset=utf-8",
        "HEADER=Accept-Language:en-us",
        //"{"email":"srcom000000032033@example.com","password":"Load32033","rememberMe":false,"grant_type":"password"}",
        BODY_BEGIN,
            "{"email":"{EmailIdFP}","password":"{PasswordFP}","grant_type":"password"}",
        BODY_END
    );
   ns_end_transaction("DT_API_CAM_OauthToken_POST", NS_AUTO_STATUS);
       
    ns_page_think_time(2.715);
    

   // SignOut:
  
    signout:
    ns_start_transaction("COM_CAM_LogoutSession");
    ns_web_url ("LogoutPage3_1",
        "URL=https://www.jcpenney.com/sessiontimeout",
        "METHOD=GET",
        "HEADER=content-type:application/json;charset=utf-8",
        "HEADER=Accept-Language:en-US,en;q=0.8",
        "HEADER=Upgrade-Insecure-Requests:1",
    );
    ns_end_transaction("COM_CAM_LogoutSession", NS_AUTO_STATUS);
    ns_page_think_time(0.325);


}
