/*-----------------------------------------------------------------------------
    Name: flow
    Generated By: cavisson
    Date of generation: 10/29/2019 07:09:55
    Flow details:
    Build details: 4.1.15 (build# 61)
    Modification History:
-----------------------------------------------------------------------------*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ns_string.h"


void flow()
{
          {
        int jpid;                              //JMS Pool Id
        int jcid;                              //JMS Connection Id
        char error_msg[1024 + 1];              // Error string. Must be 1024 size
        int ret;                               // Error code
        int msg_len = 1024;
        char msg[1024 + 1] ;        int hdr_len = 1024;
        char header[1024 + 1];        
        // Initialize KAFKA Consumer with given parameters and connection pool of pool_size
        // It returns JMS Pool ID which need to be passed for getting connection from the pool
        // In case of error, error code of value < 0 is returned and error_msg (max 1014) is set with error messag
        // (int ns_kafka_init_consumer(kafka_hostname, kafka_port, kafka_topic, consumer_group, kafka_userId, kafka_password, max_pool_size, error_msg)) 
        if((jpid = ns_kafka_init_consumer("10.207.8.55", 9092, "mosaic-stage_catalog_ack", "consumergroup_stage_catalog", "", "", 1, error_msg)) < 0)
        {
          fprintf(stderr, "Error in initializing Kafka Consumer. Error code = %d, Error Msg = %s", jpid, error_msg);
          return;
        }

        // Get connection from the connection pool.
        // This method will return connection is free or make new connection and return it.
        // In case of error, error code of value < 0 is returned and error_msg (max 1014) is set with error message.
        // Few possible errors are:
        // All connections are busy
        // Error in making connection
        // If actual connection is made, then transaction is started with name passed if it is not NULL or empty
        // If connection fails, then transaction is ended with <TxName>Error<JMSErrorCode>. For example, KAFKAConsumerConnectError2012
        if((jcid = ns_kafka_get_connection(jpid, "KAFKAConsumerConnect", error_msg)) < 0)
        {
          fprintf(stderr, "Error in getting Kafka connention. Error code = %d, Error Msg = %s", jcid, error_msg);
          return;
        }

        // Get message from JMS queue/topic using connection taken using get connection API
        // In case of error, error code of value < 0 is returned and error_msg (max 1014) is set with error message
        // Few possible errors are:
        // Connection closed by JMS server
        // Invalid connection ID passed
        // Transaction is started with name passed if it is not NULL or empty
        // If put fails, then transaction is ended with <TxName>Error<JMSErrorCode>. For example, KAFKAGetMsgError2012
        if((ret = ns_kafka_get_msg(jcid, msg, msg_len, header, hdr_len, "KAFKAGetMsg", error_msg)) < 0)
        {
          fprintf(stderr, "Error in Receiving message using Kafka connention. Error code = %d, Error Msg = %s", ret, error_msg);
	  printf("%s", msg);
        }
		printf ("*********** Recieved message= %d",ret);
		
        //This api will release the Producer connection from connection pool and it should be called every time so that another user can reuse it.
        if((jcid = ns_kakfa_release_connection(jcid, error_msg)) < 0)
        {
          fprintf(stderr, "Error in releasing Kafka connection.Error code = %d, Error Msg = %s", jcid, error_msg);
          return;
        }

        /*
        //This api will close connection with Kafka server and it should not be called every time as it will impact performance. It should be called at the end of test.
        if((ret = ns_kakfa_close_connection(jcid, "KAFKAConsumerClose" , error_msg)) < 0)
        {
        fprintf(stderr, "Error in closing Kafka connection %d", ret);
        return;
        }

        */
        // Page think time in case of adding delay for next session
        ns_page_think_time(0.0);
        }

}
