/*-----------------------------------------------------------------------------
    Name: exit_script
    Generated By: netstorm
    Date of generation: 08/30/2018 01:17:57
    Flow details:
    Build details: 4.1.10 (build# 20)
    Modification History:
-----------------------------------------------------------------------------*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ns_string.h"
#include "ns_tibco_api.h"

int exit_script()
{
    return 0;
}
