/*-----------------------------------------------------------------------------
    Name: flow
    Generated By: netstorm
    Date of generation: 08/30/2018 01:18:25
    Flow details:
    Build details: 4.1.10 (build# 20)
    Modification History:
-----------------------------------------------------------------------------*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ns_string.h"

void flow()

{
    ns_start_transaction("index");
    ns_web_url ("index_html",
        "URL=http://127.0.0.1/tours/index.html",
        "HEADER=Accept-Language:en-us",
        "HEADER=Upgrade-Insecure-Requests:1",
        "PreSnapshot=webpage_1475485357440.png",
        "Snapshot=webpage_1475485360197.png",
        INLINE_URLS,
            "URL=http://127.0.0.1/tours/Merc10-dev/images/banner_animated.gif", "HEADER=Accept-Language:en-us", "COOKIE=akaau", END_INLINE,
            "URL=http://127.0.0.1/tours/Merc10-dev/images/sun_swede.gif", "HEADER=Accept-Language:en-us", "COOKIE=akaau", END_INLINE,
            "URL=http://127.0.0.1/tours/Merc10-dev/images/login.gif", "HEADER=Accept-Language:en-us", "COOKIE=akaau", END_INLINE,
            "URL=http://127.0.0.1/tours/images/banner_merctur.jpg", "HEADER=Accept-Language:en-us", "COOKIE=akaau", END_INLINE
    );
    ns_end_transaction("index", NS_AUTO_STATUS);

}
