/*-----------------------------------------------------------------------------
    Name: init_script
    Generated By: cavisson
    Date of generation: 02/12/2019 05:02:55
    Flow details:
    Build details: 4.1.11 (build# 51)
    Modification History:
-----------------------------------------------------------------------------*/

package com.cavisson.scripts.GCP_DBSpanner_MacysMST_Memissue2;
import pacJnvmApi.NSApi;

public class init_script
{
    public static int execute(NSApi nsApi)
    {
        return 0;
    }
}
