//nsl_static_var(param1:1, File=file1.use, Refresh=USE, Mode=USE_ONCE, EncodeMode=All, UseOnceWithinTest=Yes);
//nsl_static_var(param1_new:1, File=/home/netstorm/work/scripts/nc/nc/FileParameter_RTC/file1.use, Refresh=USE, Mode=USE_ONCE, EncodeMode=All, UseOnceWithinTest=Yes, CopyFileToTR=Yes, OnUseOnceError=ABORTSESSION);
//nsl_static_var(param2:1, File=file1.unq, Refresh=USE, Mode=UNIQUE, EncodeMode=All);
nsl_static_var(param2:1, File=file1.seq, Refresh=USE, Mode=SEQUENTIAL, EncodeMode=All);
nsl_static_var(param3:1, File=file1.ran, Refresh=USE, Mode=RANDOM, EncodeMode=All);
//nsl_static_var(param2_new:1, File=/home/cavisson/file/file1.unq, Refresh=USE, Mode=UNIQUE, EncodeMode=All);
nsl_static_var(param2_new:1, File=/home/cavisson/work/file1.unq, Refresh=USE, Mode=UNIQUE, EncodeMode=All);
//nsl_static_var(wt_rm:2, File=wt.wtr, Refresh=SESSION, Mode=WEIGHTED_RANDOM, EncodeMode=All);
nsl_search_var(pm_2, PAGE=page_2, LB="<title>", RB="</title>", LBMATCH=FIRST, SaveOffset=0, RETAINPREVALUE="YES", EncodeMode=None);
nsl_search_var(pm_1, PAGE=page_1, LB="<title>", RB="</title>", LBMATCH=FIRST, SaveOffset=0, RETAINPREVALUE="YES", EncodeMode=None);
nsl_search_var(pm_3, PAGE=page_3, LB="<title>", RB="</title>", LBMATCH=FIRST, SaveOffset=0, RETAINPREVALUE="YES", EncodeMode=None);
nsl_search_var(pm_4, PAGE=page_4, LB="<title>", RB="</title>", LBMATCH=FIRST, SaveOffset=0, RETAINPREVALUE="YES", EncodeMode=None);
nsl_search_var(pm_5, PAGE=page_5, LB="<title>", RB="</title>", LBMATCH=FIRST, SaveOffset=0, RETAINPREVALUE="YES", EncodeMode=None);
nsl_search_var(pm_6, PAGE=page_6, LB="<title>", RB="</title>", LBMATCH=FIRST, SaveOffset=0, RETAINPREVALUE="YES", EncodeMode=None);
//nsl_static_var(uname:1, File=/home/netstorm/work/file.unq, Refresh=SESSION, Mode=UNIQUE, FirstDataLine=1, EncodeMode=All);
//nsl_web_find(TEXT="\"success\":true,\"currentWalletItems\":[{\"id\":\"", PAGE=page_1, FAIL=NOTFOUND, ActionOnFail=CONTINUE);
//nsl_web_find(TEXT="mhj", PAGE=page_2, FAIL=NOTFOUND, ID="Match not found", ActionOnFail=STOP);
nsl_search_var(pm1, PAGE=page_1, LB/BINARY/RE="<title>", RB/BINARY/RE="</title>", LBMATCH=FIRST, SaveOffset=0, RETAINPREVALUE="YES", EncodeMode=None);
nsl_search_var(pm2, PAGE=page_2, LB/BINARY/RE="<title>", RB/BINARY/RE="</title>", LBMATCH=FIRST, SaveOffset=0, RETAINPREVALUE="YES", EncodeMode=None);
nsl_search_var(pm3, PAGE=page_3, LB/BINARY/RE="<title>", RB/BINARY/RE="</title>", LBMATCH=FIRST, SaveOffset=0, RETAINPREVALUE="YES", EncodeMode=None);
nsl_search_var(pm4, PAGE=page_4, LB/BINARY/RE="<title>", RB/BINARY/RE="</title>", LBMATCH=FIRST, SaveOffset=0, RETAINPREVALUE="YES", EncodeMode=None);
nsl_search_var(pm5, PAGE=page_5, LB/BINARY/RE="<title>", RB/BINARY/RE="</title>", LBMATCH=FIRST, SaveOffset=0, RETAINPREVALUE="YES", EncodeMode=None);
nsl_search_var(pm6, PAGE=page_6, LB/BINARY/RE="<title>", RB/BINARY/RE="</title>", LBMATCH=FIRST, SaveOffset=0, RETAINPREVALUE="YES", EncodeMode=None);
nsl_search_var(pm7, PAGE=page_7, LB/BINARY/RE="<title>", RB/BINARY/RE="</title>", LBMATCH=FIRST, SaveOffset=0, RETAINPREVALUE="YES", EncodeMode=None);
//nsl_date_var(pm_2, Format="%d/%m/%Y", Unique=YES, DayType=WORKING, Offset=-0.01:00:00, Refresh=SESSION);
//nsl_date_var(pm_1, Format="%d/%m/%Y", DayType=WORKING, Offset=0.01:00:00, Refresh=USE);
