/*-----------------------------------------------------------------------------
    Name: flow
    Generated By: cavisson
    Date of generation: 11/02/2019 11:41:03
    Flow details:
    Build details: 4.1.15 (build# 99)
    Modification History:
-----------------------------------------------------------------------------*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ns_string.h"


void flow()
{
          {
        int jpid;                              //JMS Pool Id
        int jcid;                              //JMS Connection Id
        char error_msg[1024 + 1];              // Error string. Must be 1024 size
        int ret;                               // Error code
        char *msg = "Cavisson";            // Message to be produced
        int msg_len = strlen(msg);             // Message Length
        
        // Initialize KAFKA Consumer with given parameters and connection pool of pool_size
        // It returns JMS Pool ID which need to be passed for getting connection from the pool
        // In case of error, error code of value < 0 is returned and error_msg (max 1014) is set with error messag
        // ((int ns_kafka_init_producer(kafka_hostname, kafka_port, kafka_topic, kafka_userId, kafka_password, max_pool_size, error_msg)) 
        if((jpid = ns_kafka_init_producer("10.10.30.18", 9092, "Amol", "", "", 100, "error_msg")) < 0)
        {
          fprintf(stderr, "Error in initializing Kafka producer. Error code = %d, Error Msg = %s", jpid, error_msg);
          return;
        }

        //This api will initialize kafka security protocol
        //ns_kafka_set_security_protocol(jpid, security_protocol, error_msg)
        if((ret = ns_kafka_set_security_protocol(jpid, "ssl", error_msg)) < 0)
        {
          fprintf(stderr, "Error in setting Kafka security protocol. Error code = %d, Error Msg = %s", ret, error_msg);
          return;
        }

        //SSL config apis are required only if ssl protocol is enabled for kafka
        //This api will initialize kafka ssl ca certificate file path
        //ns_kafka_set_ssl_ca_file(key, caCertifcateFilePath, error_msg)
        if((ret = ns_kafka_set_ssl_ca_file(jpid, "/home/cavisson/work_3/Mukesh/kafka/kafka_2.11-1.0.0/kohlsCA.pem", error_msg)) < 0)
        {
          fprintf(stderr, "Error in setting Kafka ssl ca certificate.Error code = %d, Error Msg = %s", ret, error_msg);
          return;
        }

        // Get connection from the connection pool.
        // This method will return connection is free or make new connection and return it.
        // In case of error, error code of value < 0 is returned and error_msg (max 1014) is set with error message
        // Few possible errors are:
        // All connections are busy
        // Error in making connection
        // If actual connection is made, then transaction is started with name passed if it is not NULL or empty
        // If connection fails, then transaction is ended with <TxName>Error<JMSErrorCode>. For example, KAFKAProducerConnectError2012
        if((jcid = ns_kafka_get_connection(jpid, "KAFKAProducerSSLConnect", error_msg)) < 0)
        {
          fprintf(stderr, "Error in getting Kafka connention. Error code = %d, Error Msg = %s", jcid, error_msg);
          return;
        }

        // Put message in the JMS queue/topic using connection taken using get connection API
        // In case of error, error code of value < 0 is returned and error_msg (max 1014) is set with error message
        // Few possible errors are:
        // Connection closed by JMS server
        // Invalid connection ID passed
        // Transaction is started with name passed if it is not NULL or empty
        // If put fails, then transaction is ended with <TxName>Error<JMSErrorCode>. For example, KAFKAPutMsgError2012
        if((ret = ns_kafka_put_msg(jcid, msg, msg_len, "KAFKAPutMsg", error_msg)) < 0)
        {
          fprintf(stderr, "Error in putting message using Kafka connention. Error code = %d, Error Msg = %s", ret, error_msg);
        }

        //This api will release the Producer connection from connection pool and it should be called every time so that another user can reuse it.
        if((jcid = ns_kakfa_release_connection(jcid, error_msg)) < 0)
        {
          fprintf(stderr, "Error in releasing Kafka connection.Error code = %d, Error Msg = %s", jcid, error_msg);
          return;
        }

        /*
        //This api will close connection with Kafka server and it should not be called every time as it will impact performance. It should be called at the end of test.
        if((ret = ns_kakfa_close_connection(jcid, "KAFKAProducerSSLClose" ,error_msg)) < 0 )
        {
          fprintf(stderr, "Error in closing Kafka connection %d",ret);
          return;
        }

        */
        // Page think time in case of adding delay for next session
        ns_page_think_time(0.0);
        }
}