/*-----------------------------------------------------------------------------
    Name: flow
    Generated By: cavisson
    Date of generation: 11/23/2019 04:35:04
    Flow details:
    Build details: 4.1.14 (build# 38)
    Modification History:
-----------------------------------------------------------------------------*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ns_string.h"

void flow()
{
    ns_start_transaction ("index_html");
    ns_web_url ("index_html",
        "URL=http://10.10.30.111:81/tours/index.html"
    );

    ns_end_transaction ("index_html", NS_AUTO_STATUS);
    ns_page_think_time(0);

}
